services:
    - name: docker:dind
    - name: selenium/standalone-chrome:latest
      alias: selenium

stages:
  - test

selenium_test:
  stage: test
  image: gitlab.dopingtech.net:5050/devops/dopi-react-base-image:latest
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - .m2/repository
      policy: pull-push
  before_script:
    - apt update && apt install maven -y
  script:
    - npm install -g appium@2
    - appium&
    - mvn test
  artifacts:
    expire_in: 3 day
    paths:
      - $CI_PROJECT_DIR/*
  when: always
  only:
    - nihat
